name: flakes

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - rustPlatform.rust
          - dwm
          - st
          - discord-canary
          - vivaldi-snapshot
          - vscode-insiders
          - gtk-theme-collections

    steps:
      - name: obtain maximum storage
        run: |
          sudo apt clean
          sudo swapoff -a
          sudo rm -f /swapfile
          docker rmi $(docker image ls -aq)
          sudo rm -rf /opt /usr/local || true
          df -h
      - uses: actions/checkout@v2
        with:
          ref: rolling
          fetch-depth: 0
      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz
      - name: building ${{ matrix.package }}
        run: |
          nix-shell -p nixFlakes --run 'nix --experimental-features "flakes nix-command" build \
            --print-build-logs --recreate-lock-file "$(pwd)#packages.x86_64-linux.${{ matrix.package }}"'
