name: hosts file

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1.2.0
        with:
          age: '1 day'
          skip-recent: 4
          GITHUB_TOKEN: ${{ github.token }}

  hosts:
    needs: remove-old-artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/eadwu/nixpkgs/archive/develop.tar.gz
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: generate hosts file
        run: |
          nix build --out-link hosts-drv \
            .#nixosConfigurations.hosts.config._internal.eadwu.flakes.custom.hosts
          cp $(readlink -f hosts-drv) hosts
      - uses: actions/upload-artifact@v2
        with:
          name: hosts
          path: |
            hosts
