name: hosts file

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  hosts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/eadwu/nixpkgs/archive/develop.tar.gz
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: generate hosts file
        run: |
          nix-shell -p nixUnstable --run 'nix build --out-link ./hosts-drv \
            .#nixosConfigurations.hosts.config._internal.eadwu.flakes.custom.hosts'
          nix-shell -p ripgrep --run 'rg '^0.0.0.0' "$(readlink -f ./hosts-drv)" > hosts'
      - uses: actions/upload-artifact@v2
        with:
          name: hosts
          retention-days: 1
          path: |
            hosts
